import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#ffffff',
        padding: 30,
        fontFamily: 'Helvetica'
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#f97316',
        paddingBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center'
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 5
    },
    subtitle: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 5
    },
    status: {
        fontSize: 10,
        color: '#ffffff',
        backgroundColor: '#f97316',
        padding: '4 8',
        borderRadius: 10,
        textTransform: 'uppercase'
    },
    section: {
        margin: 10,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#f97316',
        marginBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingBottom: 5
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
        justifyContent: 'space-between'
    },
    label: {
        fontSize: 10,
        color: '#6b7280',
        width: '30%'
    },
    value: {
        fontSize: 10,
        color: '#1f2937',
        width: '70%',
        fontWeight: 'medium'
    },
    dayContainer: {
        marginBottom: 15,
        backgroundColor: '#f3f4f6',
        padding: 10,
        borderRadius: 5
    },
    dayTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#374151',
        marginBottom: 5
    },
    activityItem: {
        fontSize: 10,
        marginBottom: 3,
        marginLeft: 10,
        color: '#4b5563'
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        color: '#9ca3af',
        fontSize: 8,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        paddingTop: 10
    }
});

// Create Document Component
const TripDocument = ({ trip }) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <View>
                    <Text style={styles.title}>{trip.title}</Text>
                    <Text style={styles.subtitle}>{trip.destination}</Text>
                    <Text style={styles.subtitle}>
                        {new Date(trip.start_date).toLocaleDateString()} - {new Date(trip.end_date).toLocaleDateString()}
                    </Text>
                </View>
                <View>
                    <Text style={styles.status}>{trip.status}</Text>
                </View>
            </View>

            {/* Summary Section */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Trip Details</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Total Budget:</Text>
                    <Text style={styles.value}>{trip.budget} (Est.)</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Trip Type:</Text>
                    <Text style={styles.value}>{trip.trip_type}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Group Size:</Text>
                    <Text style={styles.value}>{trip.group_size} Person(s)</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Notes:</Text>
                    <Text style={styles.value}>{trip.notes || 'No specific notes.'}</Text>
                </View>
            </View>

            {/* Itinerary Section */}
            {trip.itinerary && trip.itinerary.days && (
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Itinerary</Text>
                    {trip.itinerary.days.map((day, index) => (
                        <View key={index} style={styles.dayContainer}>
                            <Text style={styles.dayTitle}>Day {day.day}: {day.title}</Text>
                            {day.activities?.map((act, idx) => (
                                <Text key={idx} style={styles.activityItem}>
                                    • {act.time} - {act.activity}
                                </Text>
                            ))}
                        </View>
                    ))}
                </View>
            )}

            {/* Footer */}
            <Text style={styles.footer}>
                Generated by RoamIQ - Your AI Travel Companion | {new Date().toLocaleDateString()}
            </Text>
        </Page>
    </Document>
);

export default TripDocument;
